### ISSUE TITLE
update comicskingdom module

### ISSUE THREAD

**Issue by iffling** [zzamboni/grabcartoons#9]
Hi. comicskingdom.com has reworked their system since they merged with DailyInk. It is now beyond my very rusty skills, unfortunately. Would love if you could either update your comicskingdom module to work again, or else point me at some examples so I might get back up to speed on these newer php/javascript systems for my own old scripts. Thanks!

**Comment by msaxer** [comment]
@iffling I guess this one is staying broken since it's gone unfixed for 6 years.  😃 

Clearly not going to work since the domain is not even correct anymore.  I'd imagine all the subsequent parsing code is obsolete as well.  The current error message is:
`Could not retrieve http://v3.comicskingdom.net/service.php/portal?clientId=14&size=0 : 500 Can't connect to v3.comicskingdom.net:80`

Copy/paste "bug" in this comment:
`# Template for arcamax.com
$TEMPLATE{'comicskingdom.com'} =`

**Comment by kuperman** [comment]
I took a quick pass at updating the template. Should be working now. Enjoy!

**Comment by msaxer** [comment]
That did the trick!  Thanks Ben.  I like that all that date parsing logic wasn't needed anymore.

Evidently commenting on a 6 year old bug sometimes works.

**Comment by zzamboni** [comment]
Thanks @kuperman for updating the template!

One thing I noticed: the tags for the comics are now identified with a slash at the beginning (e.g. `/sherman-s-lagoon`). Is this on purpose?

BTW I'm working on fixing some of the other broken modules, will push the fixes soon.

**Comment by kuperman** [comment]
@zzamboni - That was just an oversight on my part trying to get things back up and working.

**Comment by zzamboni** [comment]
Fixed the extra slash in https://github.com/zzamboni/grabcartoons/commit/6891cb7331783d4322b7ac9c9ea5a0ff7070751a
